version: '3'
services:
  odca_search_engine:
    image: humancolossus/oca-repository:0.3.0
    container_name: oca-repository
    command: /bin/sh -c "bundle exec rackup -o 0.0.0.0"
    environment:
      - BASE_URL=http://localhost:9292
      - ES_URL=http://es01:9200
    ports:
      - 9292:9292
    networks:
      - odca

  es01:
    image: elasticsearch:8.1.2
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - data01:/usr/share/elasticsearch/data
    networks:
      - odca
    ports:
      - 9200:9200

  swagger:
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=/openapi-4.0.0.yml
    volumes:
      - ./openapi-1.0.0.yml:/usr/share/nginx/html/openapi-1.0.0.yml
      - ./openapi-2.0.0.yml:/usr/share/nginx/html/openapi-2.0.0.yml
      - ./openapi-3.0.0.yml:/usr/share/nginx/html/openapi-3.0.0.yml
      - ./openapi-4.0.0.yml:/openapi-4.0.0.yml
    networks:
      - odca
    ports:
      - 8000:8080

volumes:
  data01:
    driver: local

networks:
  odca:
    external: true
