version: '3'
services:
  odca_search_engine:
    image: humancolossus/oca-repository:v0.2.0
    container_name: ocarepository
    build: ./
    command: /bin/bash -c " bundle exec rackup -o 0.0.0.0"
    ports:
      - 9292:9292
    networks:
      - odca

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
    volumes:
      - data01:/usr/share/elasticsearch/data
    networks:
      - odca
    ports:
      - 9200:9200

  swagger:
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=/swagger.json
    volumes:
      - ./swagger.json:/swagger.json
    networks:
      - odca
    ports:
      - 8000:8080

volumes:
  data01:
    driver: local

networks:
  odca:
    external: true
