openapi: 3.0.0
info:
  description: ''
  version: 2.0.0
  title: OCA Repository
servers:
  - url: 'http://localhost:9292/api/v2'
tags:
  - name: schemas
paths:
  '/schemas':
    get:
      tags:
        - schemas
      summary: Find schemas
      parameters:
        - name: limit
          in: query
          required: false
          description: Max number of results (default 1000)
          schema:
            type: string
        - name: q
          in: query
          required: false
          description: Search in all schema fields
          schema:
            type: string
        - name: params
          in: query
          required: false
          description: Search specified schema fields
          schema:
            type: object
            additionalProperties:
              type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    hashlink:
                      type: string
                    schema:
                      $ref: '#/components/schemas/Schema'
  '/schemas/{namespace}':
    post:
      tags:
        - schemas
      summary: Add schema by JSON or ZIP file to specified namespace
      description: ''
      parameters:
        - name: namespace
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: Select JSON file to upload schema base or ZIP file to upload schema branch
      responses:
        '200':
          description: Schema hashlink
    get:
      tags:
        - schemas
      summary: Find schemas in specified namespace
      parameters:
        - name: namespace
          in: path
          required: true
          schema:
            type: string
        - name: limit
          in: query
          required: false
          description: Max number of results (default 1000)
          schema:
            type: string
        - name: q
          in: query
          required: false
          description: Search in all schema fields
          schema:
            type: string
        - name: params
          in: query
          required: false
          description: Search specified schema fields
          schema:
            type: object
            additionalProperties:
              type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    hashlink:
                      type: string
                    schema:
                      $ref: '#/components/schemas/Schema'
  '/schemas/{namespace}/{DRI}':
    get:
      tags:
        - schemas
      summary: Find schema by hashlink
      parameters:
        - name: namespace
          in: path
          required: true
          schema:
            type: string
        - name: DRI
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Schema'
  '/schemas/{namespace}/{DRI}/archive':
    get:
      tags:
        - schemas
      summary: Download schema archive
      parameters:
        - name: namespace
          in: path
          required: true
          schema:
            type: string
        - name: DRI
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
components:
  schemas:
    Schema:
      properties:
        '@context':
          type: string
          example: 'https://odca.tech/v1'
        name:
          type: string
        type:
          type: string
          example: spec/schema_base/1.0
        description:
          type: string
        classification:
          type: string
        issued_by:
          type: string
        attributes:
          type: object
          properties:
            attr1:
              type: string
            attr2:
              type: string
        pii_attributes:
          type: array
          items:
            type: string
            example: attr1
