odca:
  index:
    mapping:
      total_fields:
        limit: 10000
schema_base:
  index:
    mapping:
      total_fields:
        limit: 10000
capture_base:
  index:
    mapping:
      total_fields:
        limit: 10000
overlay:
  index:
    mapping:
      total_fields:
        limit: 10000
branch:
  index:
    mapping:
      total_fields:
        limit: 10000
