capture_base:
  mappings:
    properties:
      capture_base_sai:
        type: text
        index: false
      namespace:
        type: search_as_you_type
      attributes:
        type: search_as_you_type
      flagged_attributes:
        type: search_as_you_type
meta:
  mappings:
    properties:
      capture_base_sai:
        type: text
        index: false
      suggest:
        type: completion
      namespace:
        type: search_as_you_type
      name:
        type: search_as_you_type
      description:
        type: search_as_you_type
